# Generated by Django 4.0.6 on 2022-08-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(default='userNotFound', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
